# Generated by Django 3.0 on 2019-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
