# Generated by Django 3.0 on 2019-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20191212_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
