# Generated by Django 3.0 on 2019-12-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20191213_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
